#!/bin/env zsh

SESSION_NAME="ghsty"
SESSION_RANGE=0..9

# check for unattached ghsty session 
for i in {$SESSION_RANGE}; do
  tmux has-session -t $SESSION_NAME$i 2>/dev/null
  if [ $? -eq 0 ]; then
    tmux list-clients -t $SESSION_NAME$i | grep -q attached
    if [ $? -eq 1 ]; then
      # session exists and none connected => attach
      tmux attach-session -t $SESSION_NAME$i
      break
    fi
  else
    # session doesn't exist => create
    tmux new-session -s $SESSION_NAME$i -d
    tmux attach-session -t $SESSION_NAME$i
    break
  fi
done

# vim:ts=2 sw=2 et:
