wallpaper {
	monitor = eDP-1
	path = ~/pictures/wallpapers/wallpaper
	fit_mode = cover
}
wallpaper {
	monitor = 
	path = ~/pictures/wallpapers/wallpaper
	fit_mode = cover
}

#enable splash text rendering over the wallpaper
splash = true

#vim:ts=2 sw=2 et:
