wallpaper {
	monitor = eDP-1
	path = ~/pictures/wallpapers/solo-leveling-arise-sung-jinwoo-dagger-4k.jpg
	fit_mode = cover
}
wallpaper {
	monitor = 
	path = ~/pictures/wallpapers/solo-leveling-arise-sung-jinwoo-dagger-4k.jpg
	fit_mode = cover
}

#enable splash text rendering over the wallpaper
splash = true

#vim:ts=2 sw=2 et:
