#!/bin/zsh

# sdl-freerdp3 /v:192.168.98.62 /u:Timo /p:$(op read -n "op://Private/sgic242a4nhyihwbx76ms3w5vq/password") /dynamic-resolution /sound /microphone +clipboard +aero -decorations
sdl-freerdp3 /v:192.168.98.62 /u:Timo /p:$(op read -n "op://Private/sgic242a4nhyihwbx76ms3w5vq/password") /smart-sizing:1920x1080 /sound /microphone +clipboard +aero -decorations
