#!/bin/zsh

export SEARCHPATHS=( ~ ~/github ~/.config/* ~/downloads ~/work )

#####################################################
# CTRL-T - new tmux session with selected directory #
#####################################################

tmux-sessionizer() {
  exec </dev/tty
  exec <&1

  source ~/.config/zsh/sessionizer

  zle reset-prompt
}

zle     -N            tmux-sessionizer
bindkey -M emacs '^T' tmux-sessionizer
bindkey -M vicmd '^T' tmux-sessionizer
bindkey -M viins '^T' tmux-sessionizer

#######################################
# CTRL-S - cd into selected directory #
#######################################

fzf-file-widget() {
  source ~/.config/zsh/cdonizer
  zle reset-prompt
}

zle     -N            fzf-file-widget
bindkey -M emacs '^S' fzf-file-widget
bindkey -M vicmd '^S' fzf-file-widget
bindkey -M viins '^S' fzf-file-widget

fzf-history-widget() {
  source ~/.config/zsh/histonizer

  zle vi-fetch-history -n $BUFFER
  zle end-of-line
  zle reset-prompt
}

zle     -N            fzf-history-widget
bindkey -M emacs '^R' fzf-history-widget
bindkey -M vicmd '^R' fzf-history-widget
bindkey -M viins '^R' fzf-history-widget

run-fg() {
  fg
  zle reset-prompt
}

zle     -N            run-fg
bindkey -M emacs '^Z' run-fg
bindkey -M vicmd '^Z' run-fg
bindkey -M viins '^Z' run-fg

# vim:ts=2 sw=2 et:
